version: '3.9'
services:
  hanko-migrate:
    build: ../../backend
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    command: --config /etc/config/config.yaml migrate up
    restart: on-failure
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - intranet
  webserver:
    image: nginx
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - hanko
      - elements
      - quickstart
    restart: unless-stopped
    volumes:
      - '../../quickstart/keys/:/etc/config/keys/'
      - './nginx-reverse-proxy.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - "443:443" # reverse proxied to quickstart port 8888
      - "444:444" # reverse proxied to backend hanko API port 8000
      - "1444:1444" # reverse proxied to backend hanko admin API port 8001
      - "445:445" # reverse proxied to frontend elements port 9500
    networks:
      - intranet
  hanko:
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    build: ../../backend
    ports:
      - '8000:8000' # public
      - '8001:8001' # admin
    restart: unless-stopped
    command: serve --config /etc/config/config.yaml all
    volumes:
      - type: bind
        source: ./config.yaml
        target: /etc/config/config.yaml
    networks:
      - intranet
    environment:
      - PASSWORD_ENABLED
  postgresd:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    healthcheck:
      test: pg_isready -U hanko -d hanko
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - intranet
  elements:
    build: ../../frontend
    ports:
      - "9500:80"
    networks:
      - intranet
  quickstart:
    build: ../../quickstart
    ports:
      - "8888:8080"
    environment:
      - HANKO_URL=https://solidvillage.com:444
      - HANKO_URL_INTERNAL=http://hanko:8000
      - HANKO_ELEMENT_URL=https://solidvillage.com:445/elements.js
      - HANKO_FRONTEND_SDK_URL=https://solidvillage.com:445/sdk.modern.js
    networks:
      - intranet
  mailslurper:
#    image: marcopas/docker-mailslurper:latest
    image: sha256:d4658691ed076161bb452f36b5948ee502fb3590181ec8f84813adbe49b45e4b
    ports:
      - '8080:8080' # web UI
      - '8085:8085'
    networks:
      - intranet
networks:
  intranet:
